# Application Inventory (Go plugin)
# Key: application.inventory
#
# Run manually for testing:
#   zabbix-agent2-application_inventory.exe --standalone --verbose
#   (or with full path)
#   "C:\Program Files\Zabbix Agent 2\zabbix-agent2-application_inventory.exe" --standalone --verbose

Plugins.ApplicationInventory.System.Path=C:\Program Files\Zabbix Agent 2\zabbix-agent2-application_inventory.exe
